### ISSUE TITLE
Disables DW Editor Toolbar

### ISSUE THREAD

**Issue by rrandall117** [geco2/snippeter#3]
I just tried "snippeter" on two completely different installations of DokuWiki (one was version  2014-09-29d "Hrun", the other was  2014-09-29c "Hrun"), with two different templates... and a different set of other plugins.

In both instances the "snippeter" disabled the DW Editor Toolbar. I disabled several other plugins on the first instance (in an effort to determine whether there might be a conflict). This had no effect. On the second instance, a page automatically opened in CKEditor (which was not installed on the first instance). I clicked "CANCEL", but the page saved anyway... with all previous contents deleted (replaced with "_false_").

I un-installed CKEditor from the second instance and re-installed "snippeter" from GitHub (to ensure that I had the most current version). The DW Editor Toolbar was again disabled by "snippeter".

**Comment by geco2** [comment]
Hi,

sorry for my very late respond... Overseen the email notification and just find your issue by accidentally checking another repo. Sorry

Not sure how to support you... My wiki is constantly updated to check as soon as possible if snippeter works. Currently i'm on "Release 2014-09-29d "Hrun"" and everything seems to work.

May i ask you for further information?
Do you find any php error messages in your webserver or dedicated php logfiles?
May i ask you double check if you used the namespace for snippeter twice or exclusive?
Are you able to reduce your templates to only one mentioned in the installation guide?

Possibly i'm puzzled... But i can't see how that happens.

**Comment by geco2** [comment]
Hi Randall,

i close that one cause it seems that you ether found a solution or you are not longer interested to find a solution. Please let me know if i got that wrong and i will investigate.

Regards,

Andi

**Comment by rrandall117** [comment]
OK. I had experimented with removing some other plugins to investigate whether there was a plugin conflict, but couldn't resolve the issue. So I un-installed "snippeter" and that restored my DW Editor. I may attempt this again at some point in the future.

**Comment by kdmoyers** [comment]
I'm have same issue: DW Editor toolbar disappears with Snippeter.  Only Uninstall replaces the toolbar.

Also, although Extension Manager claims to have a 2016-01-25 version, the version installed says it is 2014-08-20, and then again complains that a new version is available.  Even manually downloading from Github, the plugin.info.txt file says it's 2014-08-20.   Not sure what to believe.

Frustrating because this plugin sounds ideal to my needs, being much much simpler than Snippets.

I'm running DW Release 2018-04-22a "Greebo"

**Comment by geco2** [comment]
Hi, just created a fix #5 that probably allow you to make use of the plugin if you are still interested. 

Regards,

Andi
